name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Determine Go Version
      id: go-version
      run: |
        goMod=$(cat go.mod)
        goVersionRegex="go (1\.[0-9\.]+)"
        if [[ $goMod =~ $goVersionRegex ]]; then
          goVersion="${BASH_REMATCH[1]}"
          echo "Go version found in go.mod: $goVersion"
          echo "go-version=$goVersion" >> $GITHUB_OUTPUT
        else
            echo "Go version not found in go.mod"
            exit 1
        fi

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ steps.go-version.outputs.go-version }}

    - name: Run Tests
      run: go test -v ./...

    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v7
      with:
        distribution: goreleaser
        version: "~> v2"
        args: release --clean
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
